version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            echo 'export CODECOV_TOKEN=d0a2a28e-148e-421b-8c5e-24fcd7aa2958' >> $BASH_ENV
      - codecov/upload:
          file: ./coverage/labPlayground/index.html
          token: d0a2a28e-148e-421b-8c5e-24fcd7aa2958
